export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGOUT_USER = 'LOGOUT_USER';

// GET
export const GET_CHILDREN_DATA = 'GET_CHILDREN_DATA';
export const GET_CHILDREN_DATA_SUCCESS = 'GET_CHILDREN_DATA_SUCCESS';

// UI
export const CHILD_SELECTED = 'CHILD_SELECTED';
export const CHILD_CLEAR = 'CHILD_CLEAR';
export const CHILD_ADD_BUTTON_CLICKED = 'CHILD_ADD_BUTTON_CLICKED';
export const CHILD_EDIT_BUTTON_CLICKED = 'CHILD_EDIT_BUTTON_CLICKED';
export const CHILD_DELETE_BUTTON_CLICKED = 'CHILD_DELETE_BUTTON_CLICKED';

// SAVE
export const SAVE_CHILD_REQUEST = 'SAVE_CHILD_REQUEST';
export const SAVE_CHILD_SUCCESS = 'SAVE_CHILD_SUCCESS';
export const SAVE_CHILD_CANCEL = 'SAVE_CHILD_CANCEL';
export const SAVE_CHILD_FAILURE = 'SAVE_CHILD_FAILURE';

// DELETE
export const DELETE_CHILD_REQUEST = 'DELETE_CHILD_REQUEST';
export const DELETE_CHILD_SUCCESS = 'DELETE_CHILD_SUCCESS';
export const DELETE_CHILD_FAILURE = 'DELETE_CHILD_FAILURE';


// ---

export const GET_CONTACTPERSONS_DATA = 'GET_CONTACTPERSONS_DATA';
export const GET_CONTACTPERSONS_DATA_SUCCESS = 'GET_CONTACTPERSONS_DATA_SUCCESS';
