import {createConstants} from '../utils/index.js';

export default createConstants(
 'LOGIN_USER_REQUEST',
 'LOGIN_USER_FAILURE',
 'LOGIN_USER_SUCCESS',
 'LOGOUT_USER',
 'FETCH_CHILDREN_DATA_REQUEST',
 'RECEIVE_CHILDREN_DATA',
 'CHILD_SELECTED',
 'CHILD_CLEAR',
 'CHILD_ADD_BUTTON_CLICKED'
);
